os: osx
osx_image: xcode11.2
language: swift
script:
- xcodebuild clean build test -project MyEssentialFeed.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
- xcodebuild clean build test -project MyEssentialFeed.xcodeproj -scheme "CI_iOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,OS=13.3,name=iPhone X" ONLY_ACTIVE_ARCH=YES